### ISSUE TITLE
how chnage the menu links

### ISSUE THREAD

**Issue by sumitdas4u** [AlexStack/Laravel-CMS#49]
my site is hosted in a subfolder but the menu link is not changed showing localhost how to change it

**Comment by AlexStack** [comment]
Hi, Normally, you can change the frontend or backend blade template to what you want. Could you upload a screenshot to show the issue?

**Comment by sumitdas4u** [comment]
![image](https://user-images.githubusercontent.com/28945509/85106447-d7137000-b229-11ea-9189-550f5e9f985c.png)

the links are not working .. need to change the link as my site is inside a folder

**Comment by AlexStack** [comment]
For your special case, you could edit the links in the backend template file:  yourlaravelproject/ resources /views /vendor /laravel-cms /backend /includes / header.blade.php. For example, change to hard links.
